name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: stock-predictor-492022
  GAR_LOCATION: europe-west1
  SERVICE_NAME: stock-predictor
  REGION: europe-west1

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
        audience: 'https://iam.googleapis.com/projects/491759488917/locations/global/workloadIdentityPools/github/providers/github'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Build and Deploy
      run: |
        gcloud builds submit \
          --tag gcr.io/$PROJECT_ID/$SERVICE_NAME:latest \
          --project=$PROJECT_ID
        
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME:latest \
          --platform managed \
          --region $REGION \
          --memory 2Gi \
          --timeout 3600 \
          --max-instances 2 \
          --set-env-vars OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
          --project=$PROJECT_ID